/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_OPENAI_API_KEY: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
    NEXT_PUBLIC_OPENAI_MODEL: process.env.NEXT_PUBLIC_OPENAI_MODEL,
    NEXT_PUBLIC_OPENAI_MAX_TOKENS: process.env.NEXT_PUBLIC_OPENAI_MAX_TOKENS,
    NEXT_PUBLIC_OPENAI_SYSTEM_PROMPT: process.env.NEXT_PUBLIC_OPENAI_SYSTEM_PROMPT,
    NEXT_PUBLIC_LEONARDO_API_KEY: process.env.NEXT_PUBLIC_LEONARDO_API_KEY,
    NEXT_PUBLIC_LEONARDO_API_BASE_URL: process.env.NEXT_PUBLIC_LEONARDO_API_BASE_URL,
    NEXT_PUBLIC_LEONARDO_MODEL_ALBEDO_XL: process.env.NEXT_PUBLIC_LEONARDO_MODEL_ALBEDO_XL,
    NEXT_PUBLIC_LEONARDO_MODEL_ANIME_XL: process.env.NEXT_PUBLIC_LEONARDO_MODEL_ANIME_XL,
    NEXT_PUBLIC_LEONARDO_MODEL_KINO_XL: process.env.NEXT_PUBLIC_LEONARDO_MODEL_KINO_XL,
    NEXT_PUBLIC_LEONARDO_ELEMENT_CUTE_EMOTES: process.env.NEXT_PUBLIC_LEONARDO_ELEMENT_CUTE_EMOTES,
    NEXT_PUBLIC_LEONARDO_CONTROLNET_STYLE_REFERENCE: process.env.NEXT_PUBLIC_LEONARDO_CONTROLNET_STYLE_REFERENCE,
    NEXT_PUBLIC_LEONARDO_CONTROLNET_CHARACTER_REFERENCE: process.env.NEXT_PUBLIC_LEONARDO_CONTROLNET_CHARACTER_REFERENCE,
    NEXT_PUBLIC_LEONARDO_DEFAULT_WIDTH: process.env.NEXT_PUBLIC_LEONARDO_DEFAULT_WIDTH,
    NEXT_PUBLIC_LEONARDO_DEFAULT_HEIGHT: process.env.NEXT_PUBLIC_LEONARDO_DEFAULT_HEIGHT,
    NEXT_PUBLIC_LEONARDO_MIN_DIMENSION: process.env.NEXT_PUBLIC_LEONARDO_MIN_DIMENSION,
    NEXT_PUBLIC_LEONARDO_MAX_DIMENSION: process.env.NEXT_PUBLIC_LEONARDO_MAX_DIMENSION,
    NEXT_PUBLIC_LEONARDO_PIXEL_LIMIT: process.env.NEXT_PUBLIC_LEONARDO_PIXEL_LIMIT,
    NEXT_PUBLIC_LEONARDO_INFERENCE_STEPS_FAST: process.env.NEXT_PUBLIC_LEONARDO_INFERENCE_STEPS_FAST,
    NEXT_PUBLIC_LEONARDO_INFERENCE_STEPS_QUALITY: process.env.NEXT_PUBLIC_LEONARDO_INFERENCE_STEPS_QUALITY,
    NEXT_PUBLIC_LEONARDO_GUIDANCE_SCALE_FAST: process.env.NEXT_PUBLIC_LEONARDO_GUIDANCE_SCALE_FAST,
    NEXT_PUBLIC_LEONARDO_GUIDANCE_SCALE_QUALITY: process.env.NEXT_PUBLIC_LEONARDO_GUIDANCE_SCALE_QUALITY,
    NEXT_PUBLIC_LEONARDO_INIT_STRENGTH_FAST: process.env.NEXT_PUBLIC_LEONARDO_INIT_STRENGTH_FAST,
    NEXT_PUBLIC_LEONARDO_INIT_STRENGTH_QUALITY: process.env.NEXT_PUBLIC_LEONARDO_INIT_STRENGTH_QUALITY,
    NEXT_PUBLIC_LEONARDO_PROMPT_STRENGTH: process.env.NEXT_PUBLIC_LEONARDO_PROMPT_STRENGTH,
  },
}

module.exports = nextConfig 